### ISSUE TITLE
Add generate diff check to make sure generated.go not changed

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#525]
## Background

`go-storage` has build a codegen `definitions` (cmd/definitions) to help generated code for our services. And services will call the codegen in `doc.go` like:

https://github.com/beyondstorage/go-service-s3/blob/4217898092e96b6c2163f4281133eebd8856d90b/doc.go#L4-L6

```go
package s3

//go:generate go run -tags tools github.com/beyondstorage/go-storage/v4/cmd/definitions service.toml
```

But new contributors could miss the code generate and send PRs with not generated code. So It's better to add a check to make sure our `generated.go` generated correctly.

Moreover, this workflow checks not only `geneated.go` but also `go.mod` / `go.sum` and so on.

## Action

We can add a new workflow called `diff_check.yml` in which we:

- setup-go
- checkout services
- run `make build`
- run `git diff` and make sure the output is empty (just we did for `gofmt`)

**Comment by burntcarrot** [comment]
Hmm, not sure about how to add it. 🤔
Would love a description so I can get a better understanding! 😀

**Comment by Xuanwo** [comment]
> Hmm, not sure about how to add it. thinking
> Would love a description so I can get a better understanding! grinning

Updated, please take a look.

**Comment by burntcarrot** [comment]
I have two options:

#### 1. Run job for each service

```
name: "diff_check"
on: [ push, pull_request ]

jobs:
  go-service-fs:
    name: go-service-fs
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: "1.15"

      - name: Checkout go-service-fs repo
        uses: actions/checkout@v2
        with:
          repository: beyondstorage/go-service-fs
          path: go-service-fs

      - name: Build
        run: make build

      - name: Git Diff
        run: if [ "$(git diff | wc -l)" -gt 0 ]; then exit 1; fi
  
  go-service-gcs:
    name: go-service-gcs
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: "1.15"

      - name: Checkout go-service-gcs repo
        uses: actions/checkout@v2
        with:
          repository: beyondstorage/go-service-gcs
          path: go-service-gcs

      - name: Build
        run: make build

      - name: Git Diff
        run: if [ "$(git diff | wc -l)" -gt 0 ]; then exit 1; fi

.... so on
```

#### 2. Run a single job and checkout all services and run build and git diff

```
name: "diff_check"
on: [ push, pull_request ]

jobs:
diff_check:
  name: diff_check
  runs-on: ubuntu-latest

  steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: "1.15"

    - name: Checkout go-service-fs repo
        uses: actions/checkout@v2
        with:
          repository: beyondstorage/go-service-fs
          path: go-service-fs

    - name: Checkout go-service-gcs repo
        uses: actions/checkout@v2
        with:
          repository: beyondstorage/go-service-gcs
          path: go-service-gcs

    ..... so on

    - name: Build
        run: make build

    - name: Git Diff
      run: if [ "$(git diff | wc -l)" -gt 0 ]; then exit 1; fi

```
